import { useEffect, useState, useCallback } from "react";
import { API_BASE_URL, fetchHistory, persistClientId, resolveClientId, scanUrl } from "./api";
import StatTiles from "./components/StatTiles";
import VerdictBarChart from "./components/VerdictBarChart";
import HistoryTable from "./components/HistoryTable";
import ExportButton from "./components/ExportButton";
import UrlChecker from "./components/UrlChecker";

function App() {
  // null until this browser has an id of its own -- from the extension
  // popup's "View my dashboard" link, a previous visit, or the first manual
  // check below. There is nothing to fetch until then.
  const [clientId, setClientId] = useState(resolveClientId);
  const [records, setRecords] = useState([]);
  const [status, setStatus] = useState("ready");
  const [error, setError] = useState(null);

  const loadHistory = useCallback(() => {
    if (!clientId) {
      setRecords([]);
      setError(null);
      setStatus("ready");
      return;
    }
    setStatus("loading");
    fetchHistory(clientId, 100)
      .then((data) => {
        setRecords(data);
        setError(null);
        setStatus("ready");
      })
      .catch((err) => {
        setError(err.message);
        setStatus("error");
      });
  }, [clientId]);

  useEffect(() => {
    loadHistory();
  }, [loadHistory]);

  // A first-time visitor has no client_id, so their first manual check mints
  // one and saves it -- from then on this dashboard accumulates their checks
  // exactly as it would an id generated by the extension. The scan itself
  // only ever inspects the URL string, so nothing here opens or fetches the
  // pasted page.
  const handleCheckUrl = useCallback(
    async (url) => {
      const targetClientId = clientId || crypto.randomUUID();
      const verdict = await scanUrl(url, targetClientId);
      if (clientId) {
        // Best-effort refresh -- the inline result has already rendered, and
        // clientId is unchanged so the effect above won't re-run on its own.
        fetchHistory(clientId, 100).then(setRecords).catch(() => {});
      } else {
        // Adopting the new id re-runs loadHistory through the effect, which
        // picks up the row this scan just wrote.
        persistClientId(targetClientId);
        setClientId(targetClientId);
      }
      return verdict;
    },
    [clientId]
  );

  const total = records.length;
  const phishingCount = records.filter((r) => r.is_phishing).length;
  const legitCount = total - phishingCount;

  return (
    <div className="min-h-screen bg-[#f9f9f7] dark:bg-[#0d0d0d]">
      <div className="px-4 sm:px-6 lg:px-8 py-8 space-y-6">
        <header className="flex items-center justify-between flex-wrap gap-3">
          <div>
            <h1 className="text-2xl font-semibold text-[#0b0b0b] dark:text-white">
              PhishGuard Dashboard
            </h1>
            <p className="text-sm text-[#52514e] dark:text-[#c3c2b7]">
              Scan history and stats from the Chrome extension
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={loadHistory}
              className="rounded-md border border-[rgba(11,11,11,0.10)] dark:border-[rgba(255,255,255,0.10)] px-3 py-1.5 text-sm font-medium text-[#0b0b0b] dark:text-white hover:bg-black/5 dark:hover:bg-white/5 transition-colors"
            >
              Refresh
            </button>
            <ExportButton clientId={clientId} records={records} />
          </div>
        </header>

        <UrlChecker onCheck={handleCheckUrl} />

        {status === "error" && (
          <div className="rounded-lg border border-[#d03b3b]/30 bg-[#d03b3b]/10 px-4 py-3 text-sm text-[#d03b3b]">
            Couldn't reach the PhishGuard backend at {API_BASE_URL} — is it
            running? ({error})
          </div>
        )}

        {status !== "error" && (
          <>
            <StatTiles total={total} phishingCount={phishingCount} legitCount={legitCount} />
            <VerdictBarChart total={total} phishingCount={phishingCount} legitCount={legitCount} />
            <HistoryTable records={records} />
          </>
        )}
      </div>
    </div>
  );
}

export default App;
